_posts/2020-04-18-Fortran-Webinar.md
This PR adds a newsletter post about the Open Source Directions Fortran webinar.
@certik please review, edit as needed, and merge.
=> add Fortran webinar newsletter post

index.html
Currently the date in the news list on the landing page is formatted as `%B %Y` (example: "February 2020").
For multiple news items in a single month, it's helpful to see a day value as well.
This PR changes the date format to `%d %b %Y` so that we have something like:
06 Apr 2020
25 Feb 2020
=> Change date format to %d %b %Y in news list

_data/curated_projects.yml, _data/nav.yml, _layouts/code_category.html, assets/css/main.css, explore/category/data-types.html, explore/category/examples.html, explore/category/graphics.html, explore/category/interfaces.html, explore/category/io.html, explore/category/libraries.html, explore/category/numerical.html, explore/category/preview.html, explore/category/programming.html, explore/category/scientific.html, explore/category/strings.html, explore/index.html, explore/projects_json.js, explore/projects_search.js, explore/search.html
Inspired by your [comment](https://github.com/fortran-lang/stdlib/issues/110#issue-551592218) @certik, I've put together a very simple and (hopefully) user-friendly community project index page.
The 'Development' top-level page has been replaced with an 'Explore' page which lists foremost the _stdlib_ and _fpm_ projects followed by a searchable index of community code packages also broken down by category.
Packages are listed centrally by metadata in a yaml file, everything else is generated.
I've populated a few popular packages to start off with.
Eventually this could involve some integration with FPM.
Search functionality is fairly rudimentary based on substrings.
I've included automated badges for github stars _etc._ as done [here](https://maulingmonkey.com/guide/cpp-vs-rust/#crates-of …
=> Add explore page for listing community projects.

compilers.md
I think the order now roughly reflects the maturity, community size and
mind-share in that order.
As the author of LFortran, I approve this change.
=> Reorder open source compilers

_layouts/page.html, _layouts/post.html, _posts/2020-02-28-J3-february-meeting.md, _posts/2020-04-06-Announcing-FortranCon-2020.md, _posts/2020-04-18-Fortran-Webinar.md, compilers.md, learn/index.md
Fixes #39
Compilers and Learn section are now highlighting correctly.
The newsletters have been switched to using the 'post' layout so that 'News' is highlighted in the navbar.
=> Fix: navbar highlighting and sign-posting

news/archive.html, news/index.html
Fixes #35.
News page shows last five posts; first post is shown in full.
Archive page formatting updated to group posts.
Nav bar highlighting fixed for news pages.
=> Update: news page to show more posts

_layouts/code_category.html, packages/index.html, packages/search.html
After #26 is merged, this will update the link at the bottom of 
the packages pages to point to PACKAGES.md which details the criteria and
process for getting a project listed in the index.
=> Update: packages footer with instructions link.

compilers.md
Every compiler from the following pages should now be listed (either
active or discontinued):
https://en.wikipedia.org/wiki/List_of_compilers#Fortran_compilers
http://fortranwiki.org/fortran/show/Compilers
https://fortran.bcs.org/2017/fortran_2003_2008_compiler_support.pdf
=> Add the rest of the Fortran compilers

_includes/mailing_list.html, _includes/news_sidebar.html, _includes/rss_feed.html, _includes/twitter.html, index.html
Adds the mailing list to the landing page and news sidebar.
It also makes a few minor imporovements such as add RSS feed to the news sidebar, and adds a heading to the Twitter component for consistency.
Fixes #47
=> 47 mailing list

_includes/mailing_list.html
If you have even better way to word this, go ahead and provide suggestions.
I want the mailing list to be a place where people can have a general discussion, announcements and other things. Not just to passively receive the latest news (Twitter is much better for that, and we already have a Twitter account).
=> Make the scope of the mailinglist broader

.github/workflows/buildPRPreview.yml, .github/workflows/buildSite.yml, .github/workflows/closePR.yml, CONTRIBUTING.md, _includes/footer.html, _includes/nav.html, _includes/news_sidebar.html, _includes/rss_feed.html, _layouts/post.html, assets/css/main.css, index.html, news/archive.html, news/index.html
This PR aims to resolve #41.
The approach here is to use github actions to explicitly build the site on push as opposed to the automatic github Jekyll build used currently; this action builds the site using Jekyll on the master branch and pushes to the 'gh-pages' branch. (Repo settings will therefore need to be changed by admin here to point to 'gh-pages' branch).
Additional actions are added for pull requests which are built and pushed to the 'gh-pages' branch under the path 'pr/<pr_number>'; therefore pull requests can be previewed at fortran-lang.org/pr/46/ for example.
To enable the 'pr/<pr_number>' sub-path, the site source has been updated such that all internal site links and references are prepended with `{{site.baseurl}}`, see …
=> Github actions build & PR preview

.github/workflows/buildPRPreview.yml, .github/workflows/buildSite.yml, .github/workflows/closePR.yml, CONTRIBUTING.md, _includes/footer.html, _includes/nav.html, _includes/news_sidebar.html, _includes/rss_feed.html, _layouts/post.html, assets/css/main.css, index.html, news/archive.html, news/index.html
This PR is identical to #46 which was reverted.
@milancurcic when the repo has been renamed and is serving from 'gh-pages', then this PR can be re-merged.
Resolves #41.
#no_preview
=> Reapply "Github actions build & PR preview" PR

_data/package_index.yml
They are both SciPy like libraries, and so should belong into
"numerical". The Scientific Codes category I think should be reserved
for more of end user applications or physics solvers, not purely
numerical libraries.
=> Change categories for fgsl and SciFortran

index.html
It seems the getting started link in the home page (https://fortran-lang.org/) above footer is broken as it still points to `tutorial/`, which was removed in this commit: https://github.com/fortran-lang/fortran-lang.org/commit/2adc5eba834fc34e90a7c0b216449db2fcecfdea#diff-94d9a081cd1256334373c8ca6fb6276c
=> Fix broken getting started link from tutorial -> learn

_data/package_index.yml
This commit adds the ParaMonte library to the list of Fortran numerical libraries. ParaMonte is a well-tested general-purpose open-source high-performance MPI/Coarray-parallel Monte Carlo simulation library implemented in the 2018-standard-complaint Fortran programming language, currently with interfaces to the C/C++/Fortran/MATLAB/Python programming languages. The project's documentation is available at: https://github.com/cdslaborg/paramonte
=>  adding the ParaMonte library 

assets/js/page_nav.js
This allows page contents to be easily added
to any page by simply adding `<ul id="page-nav"></ul>`.
This will be populated by all the `<h2>` headings on the current page.
=> Fix: page-nav script to work on any page.

_data/learning.yml
Add Steve Lionel's "Doctor Fortran" blog to the list of external resources on the Fortran language
=> Add Doctor Fortran blog to learning.yml

learn/quickstart/operators_control_flow.md
This is a minor expansion of the tutorial page on control flow.
I am not entirely happy with the current result, but I cannot figure out why (probably because it is very short when compared to the rest of the file). So any comments on these changes are welcome.
I expect to continue expanding this with `do concurrent` and tags. However, some initial feedback will be beneficial.
This pull is related to the discussion in #82.
Regards,
Fernando
=> Expand do loops with cycle and exit

_data/package_index.yml
Proposal to add WHIZARD as a Fortran project. We are a High Energy Physics Monte Carlo Event Generator, so a scientific code, predominantly in Fortran up to F03 and F08 standard. The project ships with a code generator that is written in OCaml and generates Fortran code compiled and linked as shared libraries. Our development is done in a (non-openly visible) gitlab server at the University of Siegen, whose reviewed merge requests are mirrored to our public gitlab server in Siegen and an svn repository at Hepforge. Distribution tarballs are also available via http://launchpad.net/whizard. We are using both OpenMP and MPI for parallelized Monte Carlo integration and simulation, in our development version using also non-blocking communication. Two of our team members, Wolfgang Kilian and …
=> Adding WHIZARD as a Fortran project.

_data/package_index.yml
License info is not detected automatically for this package, so add explicitly.
=> Add: license info to Futility package entry.

_data/package_index.yml
While looking for a callgraph generator I stumbled over the FortranCallGraph project (a static callgrapher), from there you can find the FortranTestGenerator (unittest framework based on Capture & Replay via Serialbox), and the serialization library Serialbox (from Swiss Meteo).
The FortranTestGenerator I'm not yet adding due to lack of documentation example code.
=> package_index: FortranCallGraph and Serialbox

_data/package_index.yml
Fixes a 2 typos in the netcdf-fortran package index entry.
=> fix typos in the netcdf-fortran entry

_posts/2020-08-01-Fortran-Newsletter-August-2020.md
I didn't notice it as part of #125, as it shows fine on GitHub, but the Jekyll Markdown formatting doesn't make the url automatically a link.
=> Make the link clickable

.github/workflows/buildPRPreview.yml, .github/workflows/buildSite.yml, assets/js/package_search.js, packages/category/fpm.html, packages/index.html, packages/package_index.json
A minimal modification to include packages from fpm-registry on the website.
They are listed in their own category ('fpm') as well as searchable via the existing search function.
This is a stopgap until we can clean this up and separate out fpm-registry like crates.io to provide more info.
=> List FPM registry packages

compilers.md
We list a total of 16 compilers on the page, so the opening line should be fixed.
=> Small fix in the opening sentence on the compilers page

README.md
I'm sorry, I don't think this PR improves the README, but opposite:
* Headings shouldn't end with colons
* "How to setup" doesn't work because "setup" is a noun. We can work to change it something like "How to set up Jekyll"
Reverts fortran-lang/fortran-lang.org#139
=> Revert "Improved Docs"

_posts/2020-10-01-Fortran-Newsletter-October-2020.md
There was an erroneous space character immediately before the `<iframe>` tag. Apparently this made it not render (??).
=> fix youtube embed

_data/package_index.yml
This PR adds wannier90 to the package index, it provides interfaces to some of the already listed open source electronic structure packages (QE, Abinit, ...).
- homepage: http://www.wannier.org/
- GH repository: https://github.com/wannier-developers/wannier90
- documentation: https://github.com/wannier-developers/wannier90/wiki
- GPL-2.0
=> Add wannier90 to package index

_data/package_index.yml
Disclaimer: *this is a project I'm personally involved with.*
This PR adds a `xtb` to the package index.
- documentation: https://xtb-docs.readthedocs.io/
- GH repository: https://github.com/grimme-lab/xtb
- builds with CMake and meson
- supports GCC 7.5 to 10.2, Intel 17 to 20, PGI 19.7 to 20.7
- OpenMP and OpenACC parallelisation
- CI testing is done for Ubuntu and OSX (no Windows yet)
- LGPL-3.0-or-later
=> Add xtb to package index

_data/package_index.yml
This PR adds NWChem to the package index, see #68.
- documentation: https://nwchemgit.github.io/
- repository: https://github.com/nwchemgit/nwchem
=> Add NWChem to package index

_data/package_index.yml
Disclaimer: *this is a project I'm personally involved with.*
This PR adds an entry for DFTB+
- GH organisation of the project: https://github.com/dftbplus
- Project homepage: https://dftbplus.org/
- the projects builds with CMake
- supports GCC7.5, GCC8.4, GCC9.2, GCC10.1, Intel 18, Intel 19, NAG 7
- MPI and/or OpenMP parallel
- documentation for DFTB+
- developer docs: https://dftbplus-develguide.readthedocs.io/en/latest/
- user docs: https://dftbplus-recipes.readthedocs.io/en/latest/
See #68
=> Add DFTB+ to package index

_layouts/code_category.html
Sorts the package index after the package names, this should make the package lists clearer.
=> Sort package index

_data/package_index.yml, _layouts/code_category.html
`license: none` should be a no-go for the package index. The package index is of course no legal advice for licensing, but the information should be as accurate as possible. A package without license is unusable by definition (for open source projects), which is unfair to packages with permissive licensing conditions.
For a simple summary see: https://choosealicense.com/no-permission/
I went through all the packages with `license: none` and tried to identify the licenses. I also tried to correct all licenses which are not valid SPDX license identifiers. Many missing licenses were malformatted BSD or MIT licenses, but some had actually interesting licensing condition like original MIT license with changes under BSD-3-Clause and so on.
There are still some issues with the GPL-2.0, and …
=> Correct license identifiers

_data/package_index.yml
I wonder why this one is missing here
- GH repository: https://github.com/aradi/fypp
- documentation: https://fypp.readthedocs.io
=> Add fypp to package index

_data/learning.yml
I plan to migrate information from there to fortran-lang.org, but until
this happens, it would be good to at least provide the link, so that
people who are new to Fortran can use the site to learn modern Fortran.
=> Add a link to fortran90.org

.github/workflows/gen_tweet.yaml, .github/workflows/send_tweet.yaml
Hello everyone!
As discussed in the [fortran-lang discourse](https://fortran-lang.discourse.group/t/tool-to-manage-tweets/322?u=pcosta), this PR implements a CI that:
1. Generates tweets by commenting on a PR
2. Publishes these tweets when the PR is merged
Please have a look, and feel free to test it by submitting a PR in this repo I created: [p-costa/piu-piu-sandbox](https://github.com/p-costa/piu-piu-sandbox).
If you are happy with it, to get it to work, one needs to create a twitter app, following the steps similar to those indicated here: [github.com/gr2m/twitter-together/blob/master/docs/01-create-twitter-app.md](https://github.com/gr2m/twitter-together/blob/master/docs/01-create-twitter-app.md) and add the corresponding keys and tokens to this repo.
I should thank the author of …
=> add CI for publishing on the fortran-lang twitter account upon merging a certain PR

learn/os_setup/install_gfortran.md
Since Fedora 22, `dnf` is the default package manager (instead of `yum`).
Note: the command `yum` is still availble, but is only an alias to `dnf`.
=> add dnf install gcc-gfortran for Fedora 22+

_data/package_index.yml
I was pleasantly surprised to see this previously closed-source commercially-licensed tool is now open source under MIT!
IMO, this tool is the state of the art in automatic differentiation for Fortran. It has a long history and is hence quite robust.
See also the [discussion on discourse](https://fortran-lang.discourse.group/t/automatic-differentiation-of-fortran-code-opinions/369/10).
(It doesn't have gitlab stars because it's a self-hosted instance of gitlab I think.)
=> Add: tapenade package

_data/package_index.yml
Adds https://github.com/sfilippone/psblas3
This is an established library for sparse matrix linear algebra operations. It is described in several publications.
Perhaps it will be necessary to update the license manually.
=> Add PSBLAS to package index

learn/building_programs/build_tools.md, learn/building_programs/compiling_source.md, learn/building_programs/distributing.md, learn/building_programs/include_files.md, learn/building_programs/index.md, learn/building_programs/linking_pieces.md, learn/building_programs/managing_libraries.md, learn/building_programs/runtime_libraries.md
I think the build-tools section of the building programs minibook is a bit short and the make example contains a few common gotchas, therefore I tried to update it.
I also started some minimal introductions to meson and CMake to explain the concept of high-level build systems in comparison to make. Since it is an introductory book I didn't went to much into details on using those, as this might be something for an intermediate or advanced guide.
Changes:
- replace hyphens by ~~endashs~~ emdashs
- use correct external link declaration
- rename the example source file to functions
- correct name of the generate module file set to `user_functions`
- extend the build-tools page with a detailed guide on make
- explain concept of recursively defined variables which is commonly misused in make
- …
=> Update building programs book

_posts/2020-12-01-Fortran-Newsletter-December-2020.md, community/github_stats_data/data-fortran-lang-fortran-lang.org.json, community/github_stats_data/data-fortran-lang-fpm.json, community/github_stats_data/data-fortran-lang-stdlib.json, community/github_stats_data/data-j3-fortran-fortran_proposals.json
Sorry for the late start on this.
I populated the PR updates for each project. Please review and edit if needed. I will specifically need help from:
* @gklimowicz (Classic and LLVM Flang updates)
* @certik (LFortran updates)
* @LKedward (contributors data update)
As usual, please add your name to the authors list if you add, edit, or review content.
=> December 2020 newsletter draft

_data/package_index.yml
This PR adds an entry for the [`toml-f`](https://github.com/toml-f) library. The library implements a TOML 1.0.0-rc3 compliant parser in pure Fortran. The project is currently in beta stage (there is no v1.0 release for now), but is already successfully used in fpm.
Since the projects main build system is still meson, with CMake and fpm supported as well, I think the package index is better suited than the fpm-registry.
=> Add TOML-Fortran to package index

.github/workflows/buildPRPreview.yml, .github/workflows/buildSite.yml
Fixes #184 
Github [changed the default Ruby binaries](https://github.com/actions/virtual-environments/issues/2193) on the Ubuntu CI image which affected the installation of bundler.
This PR uses the `setup-ruby` action to select the correct version of Ruby.
[Tested successfully](https://github.com/LKedward/fortran-lang.github.io/runs/1584357004) on my fork.
=> Use setup-ruby 2.7 to fix CI build

_data/learning.yml, learn/building_programs/project_make.md
I just gave ``make`` and Fortran another try and realized again why I dropped it from *all* my project in the first place. Nevertheless, the attempt of writing this up might still be helpful for somebody learning ``make``.
The idea of the guide is the following, take a real world example from the Fortran package index with medium complexity (more than one source file, but not a huge project), which is not using ``make`` as build system and describe the process of porting it to ``make`` as insightful as possible.
This guide describes:
- creating simple functions
- creating maps in ``make``
- foreach loops over lists
- using eval to generate ``make`` expressions from lists
- handling of dependencies
- partly generating the ``Makefile`` with external tools
- wildcard functionality to detect …
=> Add in-depth introduction for Fortran with make

_data/package_index.yml
This should add *all* the remaining packages from https://github.com/fortran-lang/fortran-lang.org/issues/68 which have an open source license.
*Important:* since my background is electronic structure theory, I'm mostly not familiar with weather modeling or astrodynamics, which many of those projects are targeting. Somebody with experience in this fields should have a look over the descriptions and add tags as appropriate.
This PR will eventually close https://github.com/fortran-lang/fortran-lang.org/issues/68.
=> Add missing packages from list of popular Fortran projects

community/index.html
The fpm contributing guidelines are not yet linked from the webpage. This PR adds links on the community page to the fpm contributor guide.
=> Add links to fpm contributing guidelines

compilers.md, learn/os_setup/choose_compiler.md, learn/os_setup/index.md
This is a minor correction PR about INTEL and NVIDIA (former PGI) at both the "compilers" page and at the mini-book "setting up your os".
=> Correct Compiler page and tutorial regarding Intel oneAPI and PGI to NVIDIA

.github/workflows/buildSite.yml, packages/category/fpm.html
Joins arrays of author/maintainer names with `" and "`.
Also, simplifies fetching of registry in workflow file.
=> Fix author/maintainer output in fpm registry

CONTRIBUTING.md, PACKAGES.md, _includes/footer.html, _includes/nav.html, _layouts/code_category.html, index.html, packages/index.html, packages/search.html
I noticed recently that all links to the repo at fortran-lang.org actually reference fortran-lang.github.io the default name of a GitHub pages hosted side. The link https://github.com/fortran-lang/fortran-lang.github.io still redirects correctly to this project, yet the documentation and guides seemed a bit inconsistent too me.
Also renames three instances of master branch to default branch.
=> Rename all instances of fortran-lang.github.io to fortran-lang.org

compilers.md
- LLVM renamed their default branch from master to main
Fixes #198
=> Fix broken link for LLVM flang

_data/package_index.yml
Add packages suggested in https://fortran-lang.discourse.group/t/some-fortran-related-sites-and-packages/712
- [Illustrate](https://github.com/ccsb-scripps/illustrate)
- [Tinker](https://github.com/TinkerTools/tinker) (no open-source license)
- [eT](https://gitlab.com/eT-program/eT)
- [Siesta](https://gitlab.com/siesta-project/siesta)
- [Dalton](https://gitlab.com/dalton/dalton)
- [LSDalton](https://gitlab.com/dalton/lsdalton)
- [BigDFT](https://gitlab.com/l_sim/bigdft-suite) (no open-source license)
Only merge after #196
=> Add more electronic structure and atomistic simulation packages

compilers.md
Closes https://github.com/fortran-lang/fortran-lang.org/issues/213
Closes https://github.com/fortran-lang/fortran-lang.org/issues/214
=> Add information about free compiler versions

_data/package_index.yml
DelaunaySparse is an open source Fortran 2003 package, recently published in ACM TOMS (Algorithm 1012) for performing piecewise linear interpolation via a sparse subset of the Delaunay mesh in high-dimensional spaces.  The publication process was subject to peer-review, not only of the paper, but also the source code, which is also published in the collected algorithms of ACM TOMS.  The code itself is open source (MIT license).  This code has been in development for almost 4 years and tested on thousands of real-world and synthetic data sets.  It is in a stable condition and in usage at several national labs and universities.  Features robust error-handling and C + Python interfaces.  Unfortunately, we do not have "5 stars" yet on Github.  Please consider including anyway.
=> Added DelaunaySparse to package list

learn/quickstart/variables.md
Pointed out at https://news.ycombinator.com/item?id=26452715
=> Correct value of pi in quickstart mini-book

_data/learning.yml, learn/index.html
Just the awesome list collected by @ivan-pi in https://github.com/fortran-lang/fortran-lang.org/issues/200#issuecomment-776134553 for now.
Closes #200
=> Include learn resources to online courses

_data/package_index.yml
Ondrej requested I add Gemini3D. I added / updated a few more packages.
=> Adding packages

_data/package_index.yml
I just discovered this application, written in Fortran:
https://github.com/merzlab/QUICK
I think it should be added.
=> Add QUICK to packages

_data/package_index.yml
This patch adds the conformer-rotamer ensemble search tool ([crest](https://github.com/grimme-lab/crest)) to the package index.
- OpenMP based task scheduler and automation tool for exploring potential energy surfaces written in Fortran
- the package supports meson, CMake and plain make as build systems
- compiles with Intel Fortran and GFortran, requires MKL
- documentation can be found here: https://xtb-docs.readthedocs.io/en/latest/crest.html
cc @pprcht
=> Add crest program to package index

CONTRIBUTING.md, Gemfile.lock, assets/css/main.css, learn/quickstart/arrays_strings.md, learn/quickstart/derived_types.md, learn/quickstart/hello_world.md, learn/quickstart/operators_control_flow.md, learn/quickstart/organising_code.md, learn/quickstart/variables.md
I'm doing a bit of an audit of the *Quickstart Fortran Tutorial*. So far I mostly corrected some English stuff and tried to make the code style consistent within each page (but not across all pages).
I would like to make style consistent across the whole tutorial though, but that requires deciding on some things that are currently not consistent among all pages:
* code style
- indentation (2 or 4 spaces? or 3 or other?)
- whether to indent module `contains` rt. `module`, similarly for type `contains`
- when to put a space after `,` (`do` loop, arguments, indexing, etc.)
- vertical aligning of `::` and inline comments. Important?
- should the base indentation level in a given markdown code block always be 0 (perhaps making it easier to copy), or should it be > 0 if the code would be …
=> Quickstart edits

_data/package_index.yml
Dear friends, I wrote this utility :
python3 scrip for case conversion of source code files written in fixed form FORTRAN. Ignores comments, strings, escape, sequences within strings and some special words.
I created it essentially to use in my company, but during my personal time, so it's fully tested and I'm releasing as open source. I know it does not have the 3 git starts, as I just released the code, however is really easy to verify that works very well. So I hope you can embrace this contribution to the community. 
Many thanks.
David
=> Add convert_FORTRAN_case formatter to package index

_data/package_index.yml
**flook**
- Documentation: http://electronicstructurelibrary.github.io/flook/doxygen/index.html
- Source: https://github.com/ElectronicStructureLibrary/flook
- Builds with make
**LuaF**
- Source: https://chiselapp.com/user/vadimz/repository/luaf (fossil)
**aotus**
- Documentation: https://geb.sts.nt.uni-siegen.de/doxy/aotus/
- Source: https://osdn.net/projects/apes/scm/hg/aotus/ (mercurial)
- Builds with waf
**fortran-lua53**
- Source: https://github.com/interkosmos/fortran-lua53
- Builds with xmake
=> Add projects for Fortran-lua interfacing to package index

_scripts/prs.py
Fixes #283 
* removed attempted optimization that was causing merged PRs to be missed when a previously merged PR had another "update" after being merged
* unfortunately, it doesn't seem to currently be possible to sort by merge date in the API request
* for now, the whole list of merged PRs is searched, which takes a few minutes
* with progress bars if `tqdm` installed
* PR titles on new line in the generated Markdown
* sort merged PRs by merge date (earliest merged -> first in the output list)
=> PRs script updates

learn/os_setup/install_gfortran.md
Installation process for GFortran on OpenBSD.
=> Installation process for GFortran on OpenBSD

_data/package_index.yml
Thanks @Beliavsky for finding them.
* [FMM3D](https://github.com/flatironinstitute/FMM3D)
* [fmm2d](https://github.com/flatironinstitute/fmm2d)
=> Add Flatiron institute multipole libraries to the package index

_data/package_index.yml
Repository: https://github.com/arrayfire/arrayfire-fortran
See also https://fortran-lang.discourse.group/t/questions-from-a-fortran-hpc-webinar/1516/20
=> Add arrayfire-fortran to package index

compilers.md
The current verbiage for a couple compliers sounds like an advertisement vs. a reference article
=> compilers: use more objective tone

.github/workflows/buildPRPreview.yml, .github/workflows/commentAndPushPRPreview.yml
Actions triggered on "issue_comment" have access to
write permissions and repository secrets by default.
If we checkout and build untrusted code an attacker
can get access to the secrets as well. They can exe-
cute code by adding a jekyll ruby plugin in
"_plugins/malicious.rb".
To prevent this, we split the building of the site
and pushing the site to gh-pages and commenting on
the PR.
The site building is done with only read
permissions, so running untrusted code is not a
problem. If the site building finished successfully
a privileged action is triggered that then pushed
the site to the gh-pages branch and comments on the
PR.
I also added a check that prevents pushing 
".github/workflows/" files to the gh-pages branch, because
this would allow secret extraction and repository …
=> Fix insecure workflow.

_data/package_index.yml
- source at [qcxms/qcxms](https://github.com/qcxms/QCxMS)
- builds with meson, supports Intel Fortran
- [documentation](https://xtb-docs.readthedocs.io/en/latest/qcxms_doc/qcxms.html)
cc @jaythedog
=> Add QCxMS to package index

compilers.md
Author: Beliavsky; Closes #301.
=> Update Silverfrost compiler description.

_data/package_index.yml
The MPI examples were moved to another repo:
https://github.com/scivision/fortran-coarray-mpi-examples
=> remove excess 'mpi' tag from fortran2018-examples

learn/best_practices/arrays.md
I am submitting a PR for a single typo, noted by someone else on Fortran Discourse. In the future would you prefer that I wait until I have several suggested changes to make a pull request?
=> replaced "be found be found" with "be found"

learn/best_practices/floating_point.md, learn/best_practices/integer_division.md
The tutorial suggests bypassing integer division by type-casting one variable to real, i.e. to avoid `3/4 == 0`, you can do `real(3, dp) / 4`. 
While that's fine, it is often nicer to simply write `3 * 1.0_dp / 4`. This pull request updates the tutorial to note that.
In addition, the documentation now notes Fortran's default left-to-right operator precedence -- which affects one of the examples on the page about integers.
=> Alternative approach to avoiding integer division

learn/best_practices/floating_point.md, learn/best_practices/modules_programs.md, learn/best_practices/multidim_arrays.md
**I'm so sorry!** I cloned `fortran-lang.org` by mistake using `github` software and submitted this branch.
When I realized it, I found that it had been submitted, and I hope to get your forgiveness.
=> Minor fixes in Best Practices.

_posts/2021-11-01-Fortran-Newsletter-November-2021.md
There was a typo in the "author" field which caused the authors list not to be rendered in the November newsletter, as pointed out by @certik [here](https://github.com/fortran-lang/fortran-lang.org/pull/343#issuecomment-956498364).
=> Fix typo in author field

compilers.md
Hello!
I recently started learning Fortran and I like it. In Russia we have our own proprietary processor architectures Elbrus a.k.a. e2k and SPARC a.k.a. MCST-R (licensed by Sun) developed by the MCST (Moscow Center of SPARC Technologies) company. Also, MCST has own C, C++ and Fortran proprietary compiler named LCC. I think it is worth mentioning in the list of available compilers. Unfortunately, I haven't had a chance to try it yet, since the processors are not yet available to individuals.
Thanks.
=> Add MCST LCC C, C++ and Fortran compiler

_data/package_index.yml
I've just made my Fortran error handling framework compatible with fpm, so I thought it would be a good time to add to the Fortran Lang package index! Pretty certain it meets all the requirements.
Here is the repo: https://github.com/samharrison7/fortran-error-handler
Required details as follows:
```yaml
- name: fortran-error-handler
github: samharrison7/fortran-error-handler
description: Comprehensive error handling framework for Modern Fortran
categories: programming
tags: errors logging fpm
version: none
license: MIT
```
=> Adding Fortran Error Handler to packages index

_data/learning.yml, _data/package_index.yml
Missing "e" in "WG5: International Fortran Standards Committe" to Missing "e" in "WG5: International Fortran Standards committee"
it might seem a little odd for a spelling mistake but I wanted to contribute.
thanks and regards,
Henil Panchal
=> Resolves issue fortran-lang#361 Updates spelling-mistakes

learn/os_setup/text_editors.md
Modern Fortran now supports natively Language Server support (FORTRAN Intellisense), formatting (fprettify and findent)
=> Updated VS Code extensions

_data/package_index.yml
From the [website](http://librsb.sourceforge.net):
> librsb is a library for sparse matrix computations featuring the Recursive Sparse Blocks (RSB) matrix format. This format allows cache efficient and multi-threaded (that is, shared memory parallel) operations on large sparse matrices. The most common operations necessary to iterative solvers are available, e.g.: matrix-vector multiplication, triangular solution, rows/columns scaling, diagonal extraction / setting, blocks extraction, norm computation, formats conversion. The RSB format is especially well suited for symmetric and transposed multiplication variants. Most numerical kernels code is auto generated, and the supported numerical types can be chosen by the user at build time. librsb can also be built serially (without OpenMP …
=> Add librsb to package index

_data/package_index.yml
Addresses https://github.com/fortran-lang/fortran-lang.org/issues/232#issuecomment-830793321
Project homepage: http://pencil-code.nordita.org/
~~Is it okay to have both `github` and `url` fields?~~ (no need)
Elk (#390) and librsb (#389) are considered in separate pull requests.
=> Add pencil-code to package index

_data/package_index.yml
Addresses a subtask in https://github.com/fortran-lang/fortran-lang.org/issues/232
Project homepage: http://sun.stanford.edu/~rmunk/PROPACK/
[PROPACK was recently added to SciPy](https://github.com/scipy/scipy/releases) as one of the available SVD solvers.
Note pencil-code, Elk, and librsb, are handled in other pull requests.
=> Add PROPACK to package index

_layouts/default.html
Having the news feed linked in the `<head>` element makes it easier to subscribe in some software, as they can automatically detect the address of the feed this way. I’ve used the title “Fortran Newsletter” that’s also used for the feed itself .
=> Add feed link to HTML head element

learn/building_programs/project_make.md
I had to do this fix to the dependencies generator, to be able to build a project in the case when the makefile is not in the same directory as the source files. I hope this makes sense!
=> fix dependency of include files under `learn/building_programs` mini-book

_data/package_index.yml
Homepage: http://www.openmx-square.org/openfft/
The code is written in C but includes a Fortran interface. The library is used for DFT electronic structure calculation as part of the OpenMX (http://www.openmx-square.org/) library.
=> Add OpenFFT to package index

_data/package_index.yml
Homepage: http://www.2decomp.org/
cc @ThemosTsikas, are there any tags (keywords) you'd like to see from NAG's perspective? (For more context, the aim the pull request is to add 2DECOMP to the [Fortran Package Index](https://fortran-lang.org/packages/) at fortran-lang.org; the criteria for a package to be indexed are specified [here](https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md))
Note that entries other than 2Decomp are handled in separate pull requests.
=> Add 2DECOMP&FFT to package index

_data/package_index.yml
Homepage: http://slicot.org/
GitHub: https://github.com/SLICOT/SLICOT-Reference
cc @andreasvarga - The Fortran Package Index (https://fortran-lang.org/packages/) provides a searchable index of Fortran software for various purposes. Adding SLICOT to the index would help both new and existing Fortran users to easily find the package. Would you be able to provide some tags (keywords) for the SLICOT library?
The conditions that need to be fulfilled for the package to be indexed are given here: https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md
Please note, this pull request only applied to SLICOT, the other new entries are handled in separate pull requests.
=> Add SLICOT to package index

_includes/nav.html
As We are planning to finish the migration by end of next week. we would like to add a banner to the current page to make visitors aware of the upcoming migration.
Once we migrated to the sphinx based webpage this repository will be available at the default GH pages URL https://fortran-lang.github.io/fortran-lang.org and we will create a banner on the new webpage referencing the old repository in case somebody finds something missing.
Preview available at https://fortran-lang.org/pr/418/
Thanks and Regards,
Henil Shalin Panchal
CC @awvwgk
=> announcement banner for the new site of fortran-lang.org

_config.yml
This PR is to resolve https://github.com/fortran-lang/webpage/issues/222 , Please refer : https://fortran-lang.discourse.group/t/4942 .
This would add a custom canonical link tag to all the pages of the webpage.
Thanks and Regards,
Henil
CC @awvwgk @certik
=> fix canonical links for crawlers
