compilers.md

@certik I've written some proposed changes for F18 and current Flang.
This seemed like the easiest way to suggest the wording change.
Let me know if you would like something else.

Suggest some tweaks for Ondřej.

---

_data/package_index.yml

Add package: p-costa/CaNS

---

compilers.md

And describe each of them using their own words as copied from their
websites.

Add more commercial Fortran compilers

---

_posts/2020-02-28-J3-february-meeting.md

This was meant to be part of #29.

Meeting fixes

---

Gemfile.lock

Add: gemfile.lock to repository.

---

_includes/news_sidebar.html

Copied the news format from the top-level index.html
to _includes/news_sidebar.html so that it shows recent
news titles.

News sidebar displays recent news.

---

PACKAGES.md

@milancurcic and @certik I think this covers everything we discussed in #20 ?

Start document for detailing package index guidelines.

---

.github/workflows/buildPRPreview.yml

PR preview builds are triggered by a pull request
comment containing '#build_preview'.

Change PR preview trigger to comment.

---

.github/workflows/buildPRPreview.yml

Checkout pull request head and fix comment action.

Fix: pr preview action.

---

.github/workflows/buildPRPreview.yml

Fix: preview action PR checkout.

---

_data/package_index.yml

Submitting 2 graphics libraries to the registry. I couldn't find the PR template for this. Do we have any?

add f03gl and PLplot

---

compilers.md

This small PR will test PR preview functionality.

Fix: minor typo on compilers page.

---

_data/package_index.yml

I first heard about it here:
https://news.ycombinator.com/item?id=23160114

Add the MESA code

---

index.html

As suggested here:
https://github.com/fortran-lang/fortran-lang.org/pull/80#discussion_r425971804 and
https://github.com/fortran-lang/fortran-lang.org/blob/master/CONTRIBUTING.md#internal-site-links
ping @LKedward @certik

Use {{site.baseurl}} instead of relative link

---

_data/package_index.yml

Fixes #73 lapack entry in package index.

---

_includes/discourse.html
_includes/mailing_list.html
_includes/nav.html
_includes/news_sidebar.html
_includes/rss_feed.html
_includes/twitter.html
_layouts/default.html
assets/css/main.css
index.html

Resolves #85.
I also removed the social links from the news sidebar (now that they're in the navbar) and replaced them with the fortran-lang twitter feed.

Add: Navbar social icons

---

_posts/2020-06-01-Fortran-Newsletter-June-2020.md

We forgot to add Contributors to the TOC.

add Contributors section to TOC

---

CONTRIBUTING.md
MINIBOOKS.md

Minor update to workflow and adds information on styling.
Adds new guide on writing mini-book tutorials.

Update contributor guide

---

.gitignore

Add: .gitignore to repo.

---

learn/quickstart/organising_code.md

just a small hint that I find helpful

better not write all functions again

---

.github/workflows/buildPRPreview.yml

Build PR previews with `--future` flag to allow previewing of future newsletters.

Update: preview action for future posts.

---

_posts/2020-07-01-Fortran-Newsletter-July-2020.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

Will merge on July 1. Please review, edit, and approve before then.
If you make edits, please also add your name to the Authors list.

Begin draft of the July newsletter

---

assets/js/gh-contributors.js

Fixes #105.
There are still some formatting issues on mobile, but those can be addressed in a separate issue.

Fix: broken contributor plots on safari.

---

_data/learning.yml

Additional print resources as discussed on [discourse](https://fortran-lang.discourse.group/t/books-for-the-learn-page/177/5)
Closes #118.

Add learn books

---

_data/package_index.yml

One from [the list of popular Fortran projects](https://github.com/fortran-lang/stdlib/wiki/List-of-popular-open-source-Fortran-projects).
This solver is state-of-the-art for aerodynamic optimization and probably one of very few remaining mainstream finite volume CFD solvers implemented in Fortran outside of industry.
(Also an excellent example of the state-of-the-art in automatic differentiation in Fortran as discussed in <https://github.com/j3-fortran/fortran_proposals/issues/95>.)

Add: ADflow to package index.

---

.github/workflows/buildPRPreview.yml
.github/workflows/buildSite.yml
.github/workflows/closePR.yml

We have same CI issue as https://github.com/fortran-lang/fpm-registry/issues/22; this PR addresses this.
This is a small change that's been tested in fpm-registry so I will merge.

Fix CI: rollback and pin add-and-commit@v4.4.0

---

_posts/2020-10-01-Fortran-Newsletter-October-2020.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

It's that time of the month again. I summarized the website, stdlib, and fpm updates. There may be updates in merged PRs for stdlib and fpm in the next few days so we'll watch closely and make appropriate edits.
TODO @certik and @gklimowicz for their respective compiler updates. Do we have a contact for gfortran updates?
TODO @LKedward for updating the contribution data.
As usual, add your name to the authors list if you add, edit, or review content.
Will merge on Thursday, October 1.

first draft of the October 2020 newsletter

---

_data/package_index.yml
_layouts/code_category.html

Add electronic structure packages to index

---

_posts/2020-11-01-Fortran-Newsletter-November-2020.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

I populated the website updates summary.
Here's what remains:
As usual, add your name to the authors list if you add, edit, or review content.
Considering that I started this draft very last minute and also that it's the weekend, don't worry about having it ready for November 1, just do it at your convenience.
Thank you all!

November newsletter

---

_data/package_index.yml

Fix PSBLAS github address mistake

---

learn/building_programs/index.md

I have merged #156 but only later realized that we didn't add @awvwgk to the list of authors. I did so in this PR. @awvwgk are you okay with this?

Add Sebastian to the list of authors in the building-programs mini-book

---

_data/package_index.yml

- add octopus (https://gitlab.com/octopus-code/octopus)
- remove version tag from atomsk
- add version tag to libnegf

Update package index (add octopus)

---

.github/workflows/buildPRPreview.yml

- use new syntax to set environment variables

Fix build preview

---

compilers.md

Update compilers page following Intel oneAPI release.

---

_data/package_index.yml

- update eT, libmbd, siesta, illustrate

Fix package information

---

_data/learning.yml

Suggested by @Beliavsky in #202 
- Introduction to Computational Economics Using Fortran
- Fortran 2018 with Parallel Programming
Closes #202

Add books to learning section

---

_posts/2021-03-01-Fortran-Newsletter-March-2021.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

Outstanding items:
We won't have Flang news this month (@AlexisPerry on vacation), but we'll continue next month.
Anybody else, please review, edit or add anything I missed, and add yourself to authors please.

Newsletter for March 2021

---

_data/package_index.yml

Assorted changes related to tags: ensure some multi-word tags are joined by hyphens, unify equivalent tags, fix typos in a couple of tags, add missing tags.
This PR partially addresses #176.

Improve tags

---

CONTRIBUTING.md

Closes https://github.com/fortran-lang/fortran-lang.org/issues/209

Avoid unclear formulation in contributing guide

---

_posts/2021-03-09-fortran-lang-accepted-for-google-summer-of-code-2021.md

I forgot to include @marshallward. I apologize.

Update Authors in GSoC post

---

_posts/2021-04-01-Fortran-Newsletter-April-2021.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

I put together a draft for the April monthly newsletter and populated it from the repository activities. There has been a lot of activity at stdlib and fpm :tada:.
As usual, please add your name to the authors list if you add, edit, or review content.

Monthly newletter for April 2021

---

_posts/2021-04-20-First-Year.md

Should we do an anniversary post?

Add a first year announcement

---

index.html

Closes #242; Author: @Beliavsky.

Closes #242; Author: @Beliavsky

---

_posts/2021-05-01-Fortran-Newsletter-May-2021.md

I noticed the first of these when reading the newsletter. I did a brief pass looking for others though and found the other two.

Fix some links in May 2021 newsletter

---

_posts/2021-05-18-Welcome-GSoC-students.md

GSoC welcome post

---

_scripts/prs.py

Regarding #258.
Currently a script with a few command-line options; it prints markdown to stdout.
* Is this a good place to put it? (`_scripts/`)
* It would be easy to add more data about the PRs, such as author or date

Script for summarizing PRs

---

index.html
learn/quickstart/arrays_strings.md
learn/quickstart/operators_control_flow.md

Thanks to @Beliavsky for pointing those out.
Closes #268 
Closes #267 
Closes #266 
Closes #264

Grammar and typo fixes in main page and quickstart minibook

---

_posts/2021-06-01-Fortran-Newsletter-June-2021.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

It's again time to prepare our monthly newsletter. Going forward we want to start earlier to give everybody enough time to contribute and also be able to publish on time.
As usual, please add your name to the authors list if you add, edit, or review content.
---
@zmoon I used your script from #261 to prepare this post. Worked great to collect the relevant links, I'll add some feedback soon.

Monthly newsletter: June

---

_data/package_index.yml

Hello everyone,
I wrote [SNaC](https://github.com/p-costa/SNaC), a multi-block finite-difference solver for massively parallel simulations of fluid flows. Despite being young and the low number of stars, I hope you find it interesting and suitable for integrating the list of scientific codes.
Thanks in advance!
Pedro

add the SNaC package ?

---

_data/package_index.yml

- source at https://github.com/lanl/LATTE
- GPL-2.0 licensed
- support CMake and make as build system

Add LATTE tight-binding molecular dynamics code to package index

---

_posts/2021-07-01-Fortran-Newsletter-July-2021.md
community/github_stats_data/data-fortran-lang-fortran-lang.org.json
community/github_stats_data/data-fortran-lang-fpm.json
community/github_stats_data/data-fortran-lang-stdlib.json
community/github_stats_data/data-j3-fortran-fortran_proposals.json

Hi all - I've started the initial draft for this Month's newletter.
As usual, please add your name to the authors list if you add, edit, or review content.

July newsletter

---

_data/package_index.yml

Changed `url` to `github`, added licence.

Small fix in packages index

---

_data/package_index.yml

I still plan to put os into stdlib, but currently don't have time.

my software with at least 5 stars

---

_data/package_index.yml

See https://github.com/xcompact3d/Incompact3d

Add incompact3d to package index

---

_data/package_index.yml

Source: [stfc/fparser](https://github.com/stfc/fparser)

Add fparser to package index

---

_data/package_index.yml

source: https://github.com/Goddard-Fortran-Ecosystem/pFlogger
Thanks, @tclune for the link.

Add pFlogger to package index

---

_data/package_index.yml

Also corrected categories on previous submissions.  Did not notice that there was a short-list.

One more package

---

_posts/2022-01-01-Fortran-Newsletter-January-2022.md

Fixes a mistyped link to test-drive.

Fix broken link in newsletter

---

_data/learning.yml

See https://fortran-lang.discourse.group/t/2679
cc @fluidnumerics-joe

Add link to "The 'F' Word" video series

---

_posts/2022-02-01-Fortran-Newsletter-February-2022.md

Added LFortran updates for newsletter of February 2022

---

_posts/2022-02-01-Fortran-Newsletter-February-2022.md

Small fix to make authors render.

Fix author tag in February 2022 newsletter

---

learn/best_practices/allocatable_arrays.md
learn/best_practices/arrays.md
learn/best_practices/file_io.md
learn/best_practices/floating_point.md
learn/best_practices/index.md
learn/best_practices/integer_division.md

Fixed the already stated typos in the issues and some new ones that fall under better practices.

Resolves typos #377

---

_data/package_index.yml

Addresses https://github.com/fortran-lang/fortran-lang.org/issues/232#issuecomment-831353616
Homepage: https://elk.sourceforge.io/

Add Elk to package index

---

_data/package_index.yml

Added the SeisSol package listed on Issue: #232  to the package index.

Add SeisSol to package index

---

_data/package_index.yml

Homepage: https://cims.nyu.edu/cmcl/nufft/nufft.html
@lewisfish - I hope you don't mind me pinging you for help with a review. I'd appreciate if you can reviewing whether the package fulfills [the criteria](https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md) for the [Fortran package index](https://fortran-lang.org/packages/) and approve/disapprove.

Add NUFFT to package index

---

learn/intrinsics/ALLOCATED.md
learn/intrinsics/BIT_SIZE.md
learn/intrinsics/DATE_AND_TIME.md
learn/intrinsics/DIM.md
learn/intrinsics/ERFC.md
learn/intrinsics/EXP.md
learn/intrinsics/MAX.md
learn/intrinsics/MERGE_BITS.md
learn/intrinsics/MVBITS.md
learn/intrinsics/RANGE.md
learn/intrinsics/index.md

A few errata corrections and some changes discussed on Fortran Discourse.  
For some reason some changes I thought were submitted months ago did not apparently appear.  Those are larger; but resetting and starting from scratch on those because of the time that has passed and just want to start that over again.

several small updates, most based on comments on Fortran Discourse
